apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: user-management
data:
  DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DB_ENGINE: "django.db.backends.postgresql"
  DJANGO_DB_NAME: "user_management"
  DJANGO_DB_USER: "postgres"
  DJANGO_DB_HOST: "postgres-service"
  DJANGO_DB_PORT: "5432"
  SMS_PROVIDER: "mock"
  SMS_SENDER_ID: "UserManagement"