apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: user-management
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGV2LWluc2VjdXJlLWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # dev-insecure-key-change-in-production
  DJANGO_DB_PASSWORD: cG9zdGdyZXM=  # postgres
  SMS_API_KEY: ZGV2LWFwaS1rZXk=  # dev-api-key